### ISSUE TITLE
Reroute Bug

### ISSUE THREAD

**Issue by chez14** [ikkez/f3-middleware#4]
Please see [middleware.php:97](https://github.com/ikkez/f3-middleware/blob/master/lib/middleware.php#L97)

```php
$this->reroute(substr($this->f3['PATH'],0,-1).             // line 97
```

Shouldn't it be like this?

```php
$this->f3->reroute(substr($this->f3['PATH'],0,-1).             // line 97
```

**Comment by chez14** [comment]
oh this was fixed on #3

**Comment by chez14** [comment]
Could you please update the tag, so composer will reload the fixed one of this?

Thank you!

**Comment by ikkez** [comment]
👍
