### ISSUE TITLE
Match root of route as well

### ISSUE THREAD

**Issue by randohinn** [ikkez/f3-middleware#5]
Currently, if given a 

```php
\Middleware::instance()->before('GET|POST /cms/**', function(\Base $f3, $params, $alias) {
    dd($params);
});
```

The only route that does not get matched by the middleware is `whatever.com/cms`, without anything after it. Even more so, even by adding

```php

\Middleware::instance()->before('GET|POST /cms', function(\Base $f3, $params, $alias) {
    dd($params);
});
``` 
does it not get detected. Please implement a fix for this.

**Comment by ikkez** [comment]
What happens when you try `'GET|POST /cms*'`?

**Comment by randohinn** [comment]
Unintuitive, but works as intended, Advise to add an example to the Readme :)

**Comment by ikkez** [comment]
It's the framework behaviour since https://github.com/bcosca/fatfree-core/pull/119
But you're right... it's not documented apart from the changelog..mhh 🤔
