### ISSUE TITLE
is there anyway NOT do auth checks on some specific route like /signin /signup?

### ISSUE THREAD

**Issue by saobee** [ikkez/f3-middleware#6]
Hi , 
is there anyway NOT do auth checks on some route like whitelist?
```
//not check auth routes
$f3->route('GET|POST /login','Controller\Admin->login_page');
$f3->route('GET|POST /forget','Controller\Admin->forget_page');
$f3->route('GET|POST /captcha','Controller\Admin->captcha');

//all other routes need auth check
$f3->route('GET|POST /','Controller\Admin->login');
$f3->route('GET|POST /user','Controller\User->index');
//and so on...
```

**Comment by ikkez** [comment]
hi.. not the right place here for such things, but to quickly answer this: simply skip the auth check by checking the current route within your auth check function and add a whitelist in there. For other technique check f3-access plugin

**Comment by saobee** [comment]
thanks for reply,i will try to add a whitelist in auth check function
